/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Credenciales;

import Credenciales.*;
import Conexion.ConexionSQL;
import MenuDeEstudiante.MenuEstudiante;
import MenuDeProfesor.MenuProfesor;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.*;


/**
 *
 * @author pamel
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form Credenciales
     */
    public IniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_bienvenido = new javax.swing.JPanel();
        lbl_bienvenido = new javax.swing.JLabel();
        jp_campos = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        pass_password = new javax.swing.JPasswordField();
        btn_clean = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        lbl_password = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(255, 204, 0));
        setResizable(false);

        jp_bienvenido.setBackground(new java.awt.Color(0, 51, 102));
        jp_bienvenido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        lbl_bienvenido.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lbl_bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bienvenido.setText("Autenticación");

        javax.swing.GroupLayout jp_bienvenidoLayout = new javax.swing.GroupLayout(jp_bienvenido);
        jp_bienvenido.setLayout(jp_bienvenidoLayout);
        jp_bienvenidoLayout.setHorizontalGroup(
            jp_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_bienvenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jp_bienvenidoLayout.setVerticalGroup(
            jp_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bienvenidoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_bienvenido)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jp_campos.setBackground(new java.awt.Color(255, 255, 255));
        jp_campos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        lbl_username.setBackground(new java.awt.Color(255, 255, 255));
        lbl_username.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 51, 102));
        lbl_username.setText("Usuario");

        txt_username.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 51, 102));
        txt_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        pass_password.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        pass_password.setForeground(new java.awt.Color(0, 51, 102));
        pass_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        pass_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passwordActionPerformed(evt);
            }
        });

        btn_clean.setBackground(new java.awt.Color(0, 51, 102));
        btn_clean.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_clean.setForeground(new java.awt.Color(255, 255, 255));
        btn_clean.setText("Limpiar");
        btn_clean.setMaximumSize(new java.awt.Dimension(87, 26));
        btn_clean.setMinimumSize(new java.awt.Dimension(87, 26));
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiar2.png"))); // NOI18N

        btn_login.setBackground(new java.awt.Color(0, 51, 102));
        btn_login.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Ingresar");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_password.setBackground(new java.awt.Color(0, 51, 102));
        lbl_password.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 51, 102));
        lbl_password.setText("Contraseña");

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jp_camposLayout = new javax.swing.GroupLayout(jp_campos);
        jp_campos.setLayout(jp_camposLayout);
        jp_camposLayout.setHorizontalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_camposLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_logo)
                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_username)
                    .addComponent(pass_password)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_camposLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btn_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_camposLayout.setVerticalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_camposLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_camposLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_login)
                            .addComponent(btn_clean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_logo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void pass_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordActionPerformed

      //Configuración del Botón de Login
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String usuario = txt_username.getText().trim();
        String contrasena = new String(pass_password.getPassword());
        
        ConexionSQL conexion = new ConexionSQL();
        Connection conn = conexion.conectar(); //Conexion

        try {
            //Se llama al procedimiento que chequea que el usuario y contraseña sean correctos
            CallableStatement cs = conn.prepareCall("{call SP_Verificar_Usuario(?, ?, ?)}");
            cs.setString(1, usuario);
            cs.setString(2, contrasena);
            cs.registerOutParameter(3, java.sql.Types.VARCHAR);
            cs.execute();
            //Se llama al procedimiento para que que guarde el rol
            CallableStatement cr = conn.prepareCall("{call SP_Obtener_Rol(?, ?, ?)}");
            cr.setString(1, usuario);
            cr.setString(2, contrasena);
            cr.registerOutParameter(3, java.sql.Types.VARCHAR);
            cr.execute();
            //Para agregar los registros de ingreso al sistema
            CallableStatement ca = conn.prepareCall("{call SP_Registrar_Acceso(?, ?, ?)}");
            ca.setString(1, usuario);
            ca.setString(2, contrasena);
            ca.setInt(3, 1); 
            ca.execute();
            //Para que guarde al usuario actualmente logueado
            CallableStatement cu = conn.prepareCall("{call SP_Guardar_Usuario_Actual(?, ?)}");
            cu.setString(1, usuario);
            cu.setString(2, contrasena);
            cu.execute();


            //Muestra un mensaje
            String resultado = cs.getString(3);
            //JOptionPane.showMessageDialog(null, resultado);
            
            //Para obtener el rol
            String rol = cr.getString(3);
            
            if (resultado.equals("usuario o contraseña incorrectos")) {
                JOptionPane.showMessageDialog(null, resultado);
            } else {
                JOptionPane.showMessageDialog(null, "Ingreso exitoso. Rol: " + rol);

                //Abre una ventana dependiendo del rol
                if (rol.equalsIgnoreCase("Administrador")) {
                    MenuAdministrador MenuAdmin = new MenuAdministrador();
                    MenuAdmin.setVisible(true);//Se muestra la ventana del menu Administrador
                    MenuAdmin.setLocationRelativeTo(null);//colocar el frame al centro de la pantalla
                } else if (rol.equalsIgnoreCase("Estudiante")) {
                    MenuEstudiante MenuEstu = new MenuEstudiante();
                    MenuEstu.setVisible(true);//Se muestra la ventana del menu Administrador
                    MenuEstu.setLocationRelativeTo(null);//colocar el frame al centro de la pantalla
                } else if (rol.equalsIgnoreCase("Profesor")) {
                    MenuProfesor MenuProfe = new MenuProfesor();
                    MenuProfe.setVisible(true);//Se muestra la ventana del menu Administrador
                    MenuProfe.setLocationRelativeTo(null);//colocar el frame al centro de la pantalla
                }
                dispose(); // Cierra la ventana de login
            }
            cs.close();
            cr.close();
            ca.close();
            cu.close();
            conexion.desconectar();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_loginActionPerformed

      //Configuración del Botón de Clean
    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        // TODO add your handling code here:
        //Limpiar campos
        txt_username.setText(null);
        pass_password.setText(null);
    }//GEN-LAST:event_btn_cleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_login;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_bienvenido;
    private javax.swing.JPanel jp_campos;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
