/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Profesor;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Conexion.ConexionSQL;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.*;

/**
 *
 * @author pamel
 */
public class CrearProfesor extends javax.swing.JFrame {

    /**
     * Creates new form Credenciales
     */
    public CrearProfesor() {
        initComponents();
        ImageIcon icono = new ImageIcon("src/img/proteccion.png");
        setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_bienvenido = new javax.swing.JPanel();
        lbl_bienvenido = new javax.swing.JLabel();
        jp_campos = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        txt_idusuario = new javax.swing.JTextField();
        btn_clean = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        btn_registro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nombre = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        lbl_cedula = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        lbl_encargado = new javax.swing.JLabel();
        txt_especialidad = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Usuario");
        setBackground(new java.awt.Color(255, 204, 0));
        setResizable(false);

        jp_bienvenido.setBackground(new java.awt.Color(0, 51, 102));
        jp_bienvenido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        lbl_bienvenido.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lbl_bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bienvenido.setText("Crear Profesores");

        javax.swing.GroupLayout jp_bienvenidoLayout = new javax.swing.GroupLayout(jp_bienvenido);
        jp_bienvenido.setLayout(jp_bienvenidoLayout);
        jp_bienvenidoLayout.setHorizontalGroup(
            jp_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bienvenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_bienvenidoLayout.setVerticalGroup(
            jp_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bienvenidoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_bienvenido)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jp_campos.setBackground(new java.awt.Color(255, 255, 255));
        jp_campos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        lbl_username.setBackground(new java.awt.Color(255, 255, 255));
        lbl_username.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 51, 102));
        lbl_username.setText("ID Usuario");

        txt_idusuario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_idusuario.setForeground(new java.awt.Color(0, 51, 102));
        txt_idusuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_idusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idusuarioActionPerformed(evt);
            }
        });

        btn_clean.setBackground(new java.awt.Color(0, 51, 102));
        btn_clean.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_clean.setForeground(new java.awt.Color(255, 255, 255));
        btn_clean.setText("Limpiar");
        btn_clean.setMaximumSize(new java.awt.Dimension(87, 26));
        btn_clean.setMinimumSize(new java.awt.Dimension(87, 26));
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiar2.png"))); // NOI18N

        lbl_password.setBackground(new java.awt.Color(0, 51, 102));
        lbl_password.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 51, 102));
        lbl_password.setText("Nombre");

        btn_registro.setBackground(new java.awt.Color(0, 51, 102));
        btn_registro.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setText("Registrarse");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));

        lbl_nombre.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 51, 102));
        lbl_nombre.setText("Apellido");

        txt_apellido.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(0, 51, 102));
        txt_apellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });

        lbl_cedula.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cedula.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_cedula.setForeground(new java.awt.Color(0, 51, 102));
        lbl_cedula.setText("Correo");

        txt_correo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(0, 51, 102));
        txt_correo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });

        lbl_encargado.setBackground(new java.awt.Color(255, 255, 255));
        lbl_encargado.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbl_encargado.setForeground(new java.awt.Color(0, 51, 102));
        lbl_encargado.setText("Especialidad");

        txt_especialidad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_especialidad.setForeground(new java.awt.Color(0, 51, 102));
        txt_especialidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_especialidadActionPerformed(evt);
            }
        });

        txt_nombre.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 51, 102));
        txt_nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_camposLayout = new javax.swing.GroupLayout(jp_campos);
        jp_campos.setLayout(jp_camposLayout);
        jp_camposLayout.setHorizontalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jp_camposLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_camposLayout.createSequentialGroup()
                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_camposLayout.createSequentialGroup()
                                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jp_camposLayout.createSequentialGroup()
                                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_camposLayout.createSequentialGroup()
                                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(lbl_encargado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jp_camposLayout.createSequentialGroup()
                        .addComponent(lbl_logo)
                        .addGap(68, 68, 68)
                        .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btn_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jp_camposLayout.setVerticalGroup(
            jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_camposLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_camposLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl_username)
                        .addGap(18, 18, 18)
                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_password)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_encargado)
                        .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedula)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(lbl_logo))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jp_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_especialidadActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
       
        int idUsuario = Integer.parseInt(txt_idusuario.getText().trim());
        String nombre = txt_nombre.getText().trim();
        String apellido = txt_apellido.getText().trim();
        String correo = txt_correo.getText().trim();
        String especialidad = txt_especialidad.getText().trim();

        ConexionSQL conexion = new ConexionSQL();
        Connection conn = conexion.conectar();

        try {
            CallableStatement cs = conn.prepareCall("{call SP_Agregar_Profesor(?, ?, ?, ?, ?, ?)}");
            cs.setInt(1, idUsuario);
            cs.setString(2, nombre);
            cs.setString(3, apellido);
            cs.setString(4, correo);
            cs.setString(5, especialidad);
            cs.registerOutParameter(6, java.sql.Types.VARCHAR);

            cs.execute();

            String mensaje = cs.getString(6);
            JOptionPane.showMessageDialog(null, mensaje);

            
            if (mensaje.equalsIgnoreCase("El profesor se agregó correctamente.")) {
                txt_idusuario.setText("");
                txt_nombre.setText("");
                txt_apellido.setText("");
                txt_correo.setText("");
                txt_especialidad.setText("");
            }

            cs.close();
            conexion.desconectar();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL: " + ex.getMessage());
        }

        
    }//GEN-LAST:event_btn_registroActionPerformed


    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        // TODO add your handling code here:
        //Limpiar campos
        txt_idusuario.setText(null);
        txt_nombre.setText(null);
        txt_apellido.setText(null);
        txt_correo.setText(null);
        txt_especialidad.setText(null);
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void txt_idusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idusuarioActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        MenuAdminProfe AdminProfe = new MenuAdminProfe();
        AdminProfe.setVisible(true);
        AdminProfe.setLocationRelativeTo(null);//colocar el frame al centro de la pantalla
        dispose(); // Cierra la ventana de login
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_bienvenido;
    private javax.swing.JPanel jp_campos;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_encargado;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_especialidad;
    private javax.swing.JTextField txt_idusuario;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

}
